import type { Business, Category } from './types'

export const businesses: Business[] = [
  {
    id: 'valle-lumina',
    name: 'Valle Lúmina',
    location: 'Valle de Calamuchita, Córdoba',
    eyebrow: 'Reserva de experiencias',
    description:
      'Un paisaje vivo para explorar a tu propio ritmo. Encontrá senderos, sabores y momentos que quedan.',
    mapOrigin: { latitude: -32.1342, longitude: -64.4801 },
    mapScaleMeters: 10,
    waypoints: [
      { id: 'entrada', position: { x: -5.5, z: 4.5 } },
      { id: 'centro', position: { x: 0, z: 0 } },
      { id: 'fuego', position: { x: 2.4, z: -1.5 } },
      { id: 'mirador', position: { x: -4.2, z: -3.1 } },
      { id: 'arroyo', position: { x: 4.5, z: 2.6 } },
      { id: 'tirolesa', position: { x: -1.2, z: 3.8 } },
    ],
    pathSegments: [
      {
        id: 'entrada-centro',
        from: 'entrada',
        to: 'centro',
        distanceInMeters: 71,
      },
      { id: 'centro-fuego', from: 'centro', to: 'fuego', distanceInMeters: 28 },
      {
        id: 'centro-mirador',
        from: 'centro',
        to: 'mirador',
        distanceInMeters: 38,
      },
      { id: 'fuego-arroyo', from: 'fuego', to: 'arroyo', distanceInMeters: 48 },
      {
        id: 'centro-tirolesa',
        from: 'centro',
        to: 'tirolesa',
        distanceInMeters: 43,
      },
    ],
    mapFeatures: [
      {
        type: 'area',
        id: 'bosque',
        label: 'Bosque nativo',
        color: '#c7d2b8',
        points: [
          { x: -6, z: -5 },
          { x: -1, z: -5 },
          { x: -1, z: -1 },
          { x: -6, z: -1 },
        ],
      },
      {
        type: 'area',
        id: 'arroyo',
        label: 'Arroyo',
        color: '#b9d5d1',
        points: [
          { x: 2, z: -5 },
          { x: 6, z: -4 },
          { x: 6, z: -2 },
          { x: 2, z: -3 },
        ],
      },
      {
        type: 'path',
        id: 'sendero-central',
        points: [
          { x: -5.5, z: 4.5 },
          { x: -2, z: 1.2 },
          { x: 0, z: 0 },
          { x: 2.4, z: -1.5 },
          { x: 4.8, z: -2.8 },
        ],
      },
      {
        type: 'path',
        id: 'sendero-mirador',
        points: [
          { x: 0, z: 0 },
          { x: -2, z: -1.5 },
          { x: -4.2, z: -3.1 },
        ],
      },
      {
        type: 'building',
        id: 'entrada',
        label: 'Entrada',
        position: { x: -5.5, z: 4.5 },
        size: { x: 1.2, z: 0.8 },
        color: '#d8b46b',
      },
      {
        type: 'building',
        id: 'casa-fuego',
        label: 'Casa del Fuego',
        position: { x: 2.4, z: -1.5 },
        size: { x: 1.1, z: 0.9 },
        color: '#d4a078',
      },
    ],
    attractions: [
      {
        id: 'mirador-norte',
        name: 'Mirador Norte',
        category: 'nature',
        description: 'La vista más amplia del valle, al final del sendero de los molles.',
        position: { x: -4.2, z: -3.1 },
        color: '#e8b84a',
        tag: 'Imperdible',
        eta: '8 min',
        waypointId: 'mirador',
      },
      {
        id: 'casa-del-fuego',
        name: 'Casa del Fuego',
        category: 'food',
        description: 'Cocina de estación, pan de masa madre y café de especialidad.',
        position: { x: 2.4, z: -1.5 },
        color: '#e87952',
        tag: 'Abierto ahora',
        eta: '4 min',
        waypointId: 'fuego',
      },
      {
        id: 'sendero-agua',
        name: 'Sendero del Agua',
        category: 'nature',
        description: 'Un recorrido fresco junto al arroyo, con sombra durante todo el día.',
        position: { x: 4.5, z: 2.6 },
        color: '#56a9a0',
        tag: 'Tranquilo',
        eta: '12 min',
        waypointId: 'arroyo',
      },
      {
        id: 'tirolesa',
        name: 'Tirolesa del Bosque',
        category: 'adventure',
        description: 'Cruza el bosque a 18 metros de altura. Turnos cada 30 minutos.',
        position: { x: -1.2, z: 3.8 },
        color: '#d878a6',
        tag: 'Reserva previa',
        eta: '10 min',
        waypointId: 'tirolesa',
      },
      {
        id: 'punto-encuentro',
        name: 'Punto de encuentro',
        category: 'services',
        description: 'Información, objetos perdidos y primeros auxilios.',
        position: { x: 0, z: 0 },
        color: '#6b8cbd',
        tag: 'Servicios',
        eta: '2 min',
        waypointId: 'centro',
      },
    ],
  },
  {
    id: 'puerto-azul',
    name: 'Puerto Azul',
    location: 'Mar del Plata, Buenos Aires',
    eyebrow: 'Club costero',
    description: 'Mar, deporte y cocina frente al horizonte.',
    mapOrigin: { latitude: -38.0055, longitude: -57.5426 },
    mapScaleMeters: 10,
    mapFeatures: [],
    waypoints: [],
    pathSegments: [],
    attractions: [],
  },
]

export const categoryLabels: Record<Category, string> = {
  food: 'Sabores',
  adventure: 'Aventura',
  services: 'Servicios',
  nature: 'Naturaleza',
}
