import type { Business, Category } from './types'
import { localPointFromGps } from './coordinates'

const parqueSaavedraOrigin = { latitude: -34.550539413457, longitude: -58.48003697685765 }
const parqueSaavedraScaleMeters = 35
const parqueSaavedraPoint = (latitude: number, longitude: number) =>
  localPointFromGps(parqueSaavedraOrigin, { latitude, longitude }, parqueSaavedraScaleMeters)

export const businesses: Business[] = [
  {
    id: 'valle-lumina',
    name: 'Valle Lúmina',
    location: 'Valle de Calamuchita, Córdoba',
    eyebrow: 'Reserva de experiencias',
    statusLabel: 'Abierto hoy',
    description:
      'Un paisaje vivo para explorar a tu propio ritmo. Encontrá senderos, sabores y momentos que quedan.',
    mapOrigin: { latitude: -32.1342, longitude: -64.4801 },
    mapScaleMeters: 10,
    entryWaypointId: 'entrada',
    mapLabels: [
      { id: 'mirador-label', label: 'Mirador Norte', position: { x: -2.5, z: -9 } },
      { id: 'entrada-label', label: 'Entrada Principal', position: { x: -3, z: 9 } },
    ],
    waypoints: [
      { id: 'entrada', position: { x: -5.5, z: 4.5 } },
      { id: 'centro', position: { x: 0, z: 0 } },
      { id: 'fuego', position: { x: 2.4, z: -1.5 } },
      { id: 'mirador', position: { x: -4.2, z: -3.1 } },
      { id: 'arroyo', position: { x: 4.5, z: 2.6 } },
      { id: 'tirolesa', position: { x: -1.2, z: 3.8 } },
    ],
    pathSegments: [
      {
        id: 'entrada-centro',
        from: 'entrada',
        to: 'centro',
        distanceInMeters: 71,
      },
      { id: 'centro-fuego', from: 'centro', to: 'fuego', distanceInMeters: 28 },
      {
        id: 'centro-mirador',
        from: 'centro',
        to: 'mirador',
        distanceInMeters: 38,
      },
      { id: 'fuego-arroyo', from: 'fuego', to: 'arroyo', distanceInMeters: 48 },
      {
        id: 'centro-tirolesa',
        from: 'centro',
        to: 'tirolesa',
        distanceInMeters: 43,
      },
    ],
    mapFeatures: [
      {
        type: 'area',
        id: 'bosque',
        label: 'Bosque nativo',
        color: '#c7d2b8',
        points: [
          { x: -1, z: -5 },
          { x: -1, z: -1 },
          { x: -6, z: -1 },
        ],
      },
      {
        type: 'area',
        id: 'arroyo',
        label: 'Arroyo',
        color: '#b9d5d1',
        points: [
          { x: 2, z: -5 },
          { x: 6, z: -4 },
          { x: 6, z: -2 },
          { x: 2, z: -3 },
        ],
      },
      {
        type: 'path',
        id: 'sendero-central',
        points: [
          { x: -5.5, z: 4.5 },
          { x: -2, z: 1.2 },
          { x: 0, z: 0 },
          { x: 2.4, z: -1.5 },
          { x: 4.8, z: -2.8 },
        ],
      },
      {
        type: 'path',
        id: 'sendero-mirador',
        points: [
          { x: 0, z: 0 },
          { x: -2, z: -1.5 },
          { x: -4.2, z: -3.1 },
        ],
      },
      {
        type: 'building',
        id: 'entrada',
        label: 'Entrada',
        position: { x: -5.5, z: 4.5 },
        size: { x: 1.2, z: 0.8 },
        color: '#d8b46b',
      },
      {
        type: 'building',
        id: 'casa-fuego',
        label: 'Casa del Fuego',
        position: { x: 2.4, z: -1.5 },
        size: { x: 1.1, z: 0.9 },
        color: '#d4a078',
      },
    ],
    attractions: [
      {
        id: 'mirador-norte',
        name: 'Mirador Norte',
        category: 'nature',
        description: 'La vista más amplia del valle, al final del sendero de los molles.',
        coordinates: { latitude: -32.1339219, longitude: -64.4805455 },
        color: '#e8b84a',
        tag: 'Imperdible',
        waypointId: 'mirador',
      },
      {
        id: 'casa-del-fuego',
        name: 'Casa del Fuego',
        category: 'food',
        description: 'Cocina de estación, pan de masa madre y café de especialidad.',
        coordinates: { latitude: -32.1340653, longitude: -64.4798455 },
        color: '#e87952',
        tag: 'Abierto ahora',
        waypointId: 'fuego',
      },
      {
        id: 'sendero-agua',
        name: 'Sendero del Agua',
        category: 'nature',
        description: 'Un recorrido fresco junto al arroyo, con sombra durante todo el día.',
        coordinates: { latitude: -32.1344333, longitude: -64.479623 },
        color: '#56a9a0',
        tag: 'Tranquilo',
        waypointId: 'arroyo',
      },
      {
        id: 'tirolesa',
        name: 'Tirolesa del Bosque',
        category: 'adventure',
        description: 'Cruza el bosque a 18 metros de altura. Turnos cada 30 minutos.',
        coordinates: { latitude: -32.134541, longitude: -64.4802272 },
        color: '#d878a6',
        tag: 'Reserva previa',
        waypointId: 'tirolesa',
      },
      {
        id: 'punto-encuentro',
        name: 'Punto de encuentro',
        category: 'services',
        description: 'Información, objetos perdidos y primeros auxilios.',
        coordinates: { latitude: -32.1342, longitude: -64.4801 },
        color: '#6b8cbd',
        tag: 'Servicios',
        waypointId: 'centro',
      },
    ],
  },
  {
    id: 'parque-saavedra',
    name: 'Parque Saavedra',
    location: 'Saavedra, Buenos Aires, Argentina',
    eyebrow: 'Parque urbano y comunidad',
    statusLabel: 'Abierto hoy',
    description:
      'Un parque para encontrarse, jugar y descansar entre árboles, juegos y espacios para todas las edades.',
    mapOrigin: parqueSaavedraOrigin,
    mapScaleMeters: parqueSaavedraScaleMeters,
    entryWaypointId: 'entrada-avenida-garcia-del-rio',
    // mapLabels: [
    //   { id: 'entrada-label', label: 'Entrada principal', position: { x: -6, z: 5 } },
    //   { id: 'calesita-label', label: 'Calesita', position: { x: -1.5, z: -2 } },
    //   { id: 'juegos-label', label: 'Patios de juego', position: { x: 3.5, z: 1.5 } },
    // ],
    waypoints: [
      { id: 'entrada-avenida-garcia-del-rio', position: { x: -6, z: 5 } },
      { id: 'rotonda-central', position: { x: 0, z: 0 } },
      { id: 'calesita', position: parqueSaavedraPoint(-34.55074166164884, -58.47773387036484) },
      { id: 'barco-pirata', position: parqueSaavedraPoint(-34.550820750228866, -58.4779983291193) },
      {
        id: 'camion-juegos',
        position: parqueSaavedraPoint(-34.551479464923645, -58.47983059439104),
      },
      { id: 'tobogan', position: parqueSaavedraPoint(-34.551408221690295, -58.481300468125255) },
      { id: 'arenero', position: parqueSaavedraPoint(-34.55000847604686, -58.48188919487784) },
      {
        id: 'cancha-futbol',
        position: parqueSaavedraPoint(-34.549663540518985, -58.48003045169727),
      },
      {
        id: 'banos-publicos',
        position: parqueSaavedraPoint(-34.55105193481853, -58.478716623324985),
      },
      { id: 'comisaria', position: parqueSaavedraPoint(-34.550443358440916, -58.4777150369438) },
    ],
    pathSegments: [
      {
        id: 'entrada-rotonda',
        from: 'entrada-avenida-garcia-del-rio',
        to: 'rotonda-central',
        distanceInMeters: 10,
        accessible: true,
      },
      {
        id: 'rotonda-calesita',
        from: 'rotonda-central',
        to: 'calesita',
        distanceInMeters: 215,
        accessible: true,
      },
      {
        id: 'rotonda-barco',
        from: 'rotonda-central',
        to: 'barco-pirata',
        distanceInMeters: 190,
        accessible: true,
      },
      {
        id: 'rotonda-camion',
        from: 'rotonda-central',
        to: 'camion-juegos',
        distanceInMeters: 120,
        accessible: true,
      },
      {
        id: 'rotonda-tobogan',
        from: 'rotonda-central',
        to: 'tobogan',
        distanceInMeters: 150,
        accessible: true,
      },
      {
        id: 'rotonda-arenero',
        from: 'rotonda-central',
        to: 'arenero',
        distanceInMeters: 190,
      },
      {
        id: 'rotonda-cancha',
        from: 'rotonda-central',
        to: 'cancha-futbol',
        distanceInMeters: 100,
      },
      {
        id: 'rotonda-banos',
        from: 'rotonda-central',
        to: 'banos-publicos',
        distanceInMeters: 180,
      },
      {
        id: 'rotonda-comisaria',
        from: 'rotonda-central',
        to: 'comisaria',
        distanceInMeters: 225,
        accessible: true,
      },
    ],
    mapFeatures: [
      {
        type: 'area',
        id: 'canopia-norte',
        label: 'Arboleda',
        color: '#c7d2b8',
        points: [
          { x: -6, z: -5 },
          { x: -1, z: -5 },
          { x: -1, z: -1 },
          { x: -6, z: -1 },
        ],
      },
      {
        type: 'area',
        id: 'jardin-sur',
        label: 'Jardín del parque',
        color: '#d6dec1',
        points: [
          { x: -5, z: 1 },
          { x: -1, z: 1 },
          { x: -1, z: 5 },
          { x: -5, z: 5 },
        ],
      },
      {
        type: 'path',
        id: 'sendero-principal',
        points: [
          { x: -6, z: 5 },
          { x: -2.5, z: 2 },
          { x: 0, z: 0 },
          { x: 3.5, z: 1.5 },
          { x: 4.5, z: -3.5 },
        ],
      },
      {
        type: 'path',
        id: 'sendero-deportivo',
        points: [
          { x: 0, z: 0 },
          { x: -3.8, z: -4 },
        ],
      },
      {
        type: 'building',
        id: 'entrada-parque',
        label: 'Entrada principal',
        position: { x: -6, z: 5 },
        size: { x: 1.2, z: 0.8 },
        color: '#d8b46b',
      },
      {
        type: 'building',
        id: 'centro-cultural',
        label: 'Centro de actividades',
        position: { x: 2.5, z: 4 },
        size: { x: 1.6, z: 1 },
        color: '#d4a078',
      },
    ],
    attractions: [
      {
        id: 'carousel',
        name: 'Carousel',
        category: 'adventure',
        description: 'A beautiful carousel located in the park.',
        coordinates: { latitude: -34.55074166164884, longitude: -58.47773387036484 },
        imageUrl:
          'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSbbFTO2Be3H5gUHhOgPxjoEzZ5iG5_9RPKbK50vSiHtXMnmdEM',
        iconUrl: '/carousel.png',
        color: '#d878a6',
        tag: 'Para toda la familia',
        waypointId: 'calesita',
      },
      {
        id: 'pirate-ship',
        name: 'Pirate Ship',
        category: 'adventure',
        description: 'A pirate ship themed playground for kids.',
        coordinates: { latitude: -34.550820750228866, longitude: -58.4779983291193 },
        imageUrl:
          'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSbbFTO2Be3H5gUHhOgPxjoEzZ5iG5_9RPKbK50vSiHtXMnmdEM',
        color: '#e8b84a',
        tag: 'Juegos infantiles',
        waypointId: 'barco-pirata',
      },
      {
        id: 'playground-truck',
        name: 'Playground Truck',
        category: 'nature',
        description: 'A truck themed playground for kids.',
        coordinates: { latitude: -34.551479464923645, longitude: -58.47983059439104 },
        imageUrl:
          'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSbbFTO2Be3H5gUHhOgPxjoEzZ5iG5_9RPKbK50vSiHtXMnmdEM',
        color: '#56a9a0',
        tag: 'Sombra y descanso',
        waypointId: 'camion-juegos',
      },
      {
        id: 'playground-slide',
        name: 'Playground Slide',
        category: 'adventure',
        description: 'A slide themed playground for kids.',
        coordinates: { latitude: -34.551408221690295, longitude: -58.481300468125255 },
        imageUrl:
          'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSbbFTO2Be3H5gUHhOgPxjoEzZ5iG5_9RPKbK50vSiHtXMnmdEM',
        color: '#6b8cbd',
        tag: 'Actividad libre',
        waypointId: 'tobogan',
      },
      {
        id: 'sandbox',
        name: 'Sandbox',
        category: 'food',
        description: 'A sandbox for kids to play in.',
        coordinates: { latitude: -34.55000847604686, longitude: -58.48188919487784 },
        imageUrl:
          'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSbbFTO2Be3H5gUHhOgPxjoEzZ5iG5_9RPKbK50vSiHtXMnmdEM',
        color: '#e87952',
        tag: 'Fines de semana',
        waypointId: 'arenero',
      },
      {
        id: 'football-field',
        name: 'Football Field',
        category: 'adventure',
        description: 'A football field for sports activities.',
        coordinates: { latitude: -34.549663540518985, longitude: -58.48003045169727 },
        imageUrl:
          'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSbbFTO2Be3H5gUHhOgPxjoEzZ5iG5_9RPKbK50vSiHtXMnmdEM',
        color: '#8b9dba',
        tag: 'Servicios',
        waypointId: 'cancha-futbol',
      },
      {
        id: 'public-restroom',
        name: 'Public Restroom',
        category: 'services',
        description: 'A public restroom in the park.',
        coordinates: { latitude: -34.55105193481853, longitude: -58.478716623324985 },
        imageUrl:
          'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSbbFTO2Be3H5gUHhOgPxjoEzZ5iG5_9RPKbK50vSiHtXMnmdEM',
        color: '#8b9dba',
        tag: 'Servicios',
        waypointId: 'banos-publicos',
      },
      {
        id: 'police-station',
        name: 'Police Station',
        category: 'services',
        description: 'The local police station.',
        coordinates: { latitude: -34.550443358440916, longitude: -58.4777150369438 },
        imageUrl:
          'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSbbFTO2Be3H5gUHhOgPxjoEzZ5iG5_9RPKbK50vSiHtXMnmdEM',
        color: '#6b8cbd',
        tag: 'Seguridad',
        waypointId: 'comisaria',
      },
    ],
  },
]

export const categoryLabels: Record<Category, string> = {
  food: 'Sabores',
  adventure: 'Aventura',
  services: 'Servicios',
  nature: 'Naturaleza',
}
